import Head from 'next/head'
import MainPage from '../components/MainPage'
import NavBar from '../components/NavBar'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <NavBar />
<MainPage />
       </div>
    </div>
  )
}
